version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: elefant123
      POSTGRES_DB: devicedb
    ports:
      - "5434:5434"
    networks:
      device_demo_net:
        ipv4_address: 172.19.0.8  # Adresa IP dorită pentru containerul PostgreSQL


  spring-app:
    build:
      context: .  # Directorul în care se află Dockerfile-ul aplicației Spring Boot
    ports:
      - "8081:8081"
    environment:
      DB_IP: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: elefant123
      DB_DBNAME: devicedb
    depends_on:
      - postgres
    networks:
      device_demo_net:
        ipv4_address: 172.19.0.9


networks:
  device_demo_net:
    external: true
